# version: '3.8'

services:
  mongo:
    image: mongo
    container_name: artha_mongo
    ports:
      - "27017:27017"
    volumes:
      - artha_mongo_data:/data/db

  redis:
    image: redis
    container_name: artha_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./server
    container_name: artha_backend
    ports:
      - "5000:5000"
    # environment:
    #   - MONGO_URI=mongodb://mongo:27017/artha
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
    environment:
      - MONGO_URI=mongodb://mongo:27017/artha-jobs
      - REDIS_URL=redis://redis:6379
      - PORT=5000

    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./client
    container_name: artha_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:5000
    depends_on:
      - backend

volumes:
  artha_mongo_data:
